name: {{cookiecutter.project_name}}
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # project-specific packages
  # required
  - codecov
  - dvc
  - dvc-gdrive
  - ipython
  - jupyterlab
  - libblas=*=*_mkl
  - nextflow
  - pip
  - pytest
  - python=3
  - r-irkernel
  # usually good to have
  - jax
  - r
  - rpy2
  - r-tidyverse
  - pandas
  - scikit-learn
  - seaborn
